// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4A7DWJaYou3JbVT3bOFiqfZj5k0ofdPA',
    appId: '1:824415892763:web:2d6644e295f2f8f96d8fbe',
    messagingSenderId: '824415892763',
    projectId: 'farmiot2-991dc',
    authDomain: 'farmiot2-991dc.firebaseapp.com',
    storageBucket: 'farmiot2-991dc.appspot.com',
    measurementId: 'G-NCLGTRJZJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyiJ5jpxSab3pcQk1Eswtau3Z0E0cQlvA',
    appId: '1:824415892763:android:17e3cac3d6d452806d8fbe',
    messagingSenderId: '824415892763',
    projectId: 'farmiot2-991dc',
    storageBucket: 'farmiot2-991dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuZ6sRHSgYJ2Cffz-nLX0GuqlC_YG1HLY',
    appId: '1:824415892763:ios:34134c3b13a2ab856d8fbe',
    messagingSenderId: '824415892763',
    projectId: 'farmiot2-991dc',
    storageBucket: 'farmiot2-991dc.appspot.com',
    iosClientId:
        '824415892763-vpbuc3u2rv08etv9vos3bj7265b08tpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmiot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuZ6sRHSgYJ2Cffz-nLX0GuqlC_YG1HLY',
    appId: '1:824415892763:ios:34134c3b13a2ab856d8fbe',
    messagingSenderId: '824415892763',
    projectId: 'farmiot2-991dc',
    storageBucket: 'farmiot2-991dc.appspot.com',
    iosClientId:
        '824415892763-vpbuc3u2rv08etv9vos3bj7265b08tpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmiot',
  );
}
